spring:
  application:
    name: Mongo DB Example
  data:
    mongodb:
      host: YouHost
      port: 53320
      database: spring-boot-jpa
      repositories:
        type: auto
      uri: YouURI/spring-boot-jpa